[data]
min_molecules_per_gene = 50
min_molecules_per_cell = 30
x = "x" # Name of the x column in the input data. Default: "x"
y = "y" # Name of the y column in the input data. Default: "y"

[segmentation]
scale = 50 # ~ expected (smallest?) cell radius
n_clusters = 15 # adviced for data with cell compartment structure? TODO: why?

[plotting]
gene_composition_neigborhood = 70
